CREATE TABLE [dbo].[Player]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY(1, 1),
	[Guid] UNIQUEIDENTIFIER NOT NULL UNIQUE,
	[UserName] NVARCHAR(100) NOT NULL UNIQUE,
	[CreatedAtDateUTC] DATETIME NOT NULL DEFAULT GETUTCDATE()
)
